podSpec:
  automountServiceAccountToken: true
  serviceAccountName: sonobuoy-test-robot
  volumes:
  - name: cache-volume
    emptyDir: {}
  # initContainers:
  # - name: git-cloner
  #   image: alpine/git
  #   args:
  #       - clone
  #       - --single-branch
  #       - --
  #       - $TEST_REPO_URL
  #       - /tmp/repo
  #   volumeMounts:
  #   - mountPath: /tmp/repo
  #     name: cache-volume
sonobuoy-config:
  driver: Job
  plugin-name: terratest
  result-format: gojson
spec:
  image: terratest-k8s-sonobuoy-playground:dirty
  name: plugin
  #args:
  #- $REPO_URL REPO_TEST_PATH
  volumeMounts:
  - mountPath: /mnt/repo
    name: cache-volume  